[package]
name = "fast_instruction"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Utilities for optimizing Solana smart contract development."
repository = "https://github.com/ergonia/fast_instruction"
readme = "README.md"
keywords = ["solana", "performance", "optimization", "smart-contract"]
categories = ["cryptography::blockchain", "development-tools"]
authors = ["Ergonia"]

[dependencies]
solana-program = { version = "1.8", optional = true }
pinocchio = { version = "0.7", optional = true }

bytemuck = { version = "1.18.0", features = ["derive"] }
arbitrary = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[features]
default = ["solana-sdk"]
# Feature to select Solana SDK
solana-sdk = ["dep:solana-program"]
# Feature to select Pinocchio SDK
pinocchio-sdk = ["dep:pinocchio"]

fuzzing = ["dep:arbitrary"]
